# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.tmp = {
    useTmpfs = true;
    tmpfsSize = "8G";
  };

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelParams = [ "amd_iommu=on" "iommu=pt" ];
  boot.kernelModules = [ "kvm-amd" ];
  # boot.kernelModules = [ "kvm-amd" "vfio" "vfio_iommu_type1" "vfio_pci" "vfio_virqfd" ];
  # boot.extraModprobeConfig = ''
  #   options vfio-pci ids=8086:e20b,8086:e2f7
  # '';
  boot.extraModulePackages = [ ];

  # 禁用 usb 设备唤醒
  services.udev.extraRules = ''
    ACTION=="add", SUBSYSTEM=="usb", ATTR{power/wakeup}="disabled"
  '';

  fileSystems."/mnt/ntfs" = {
    device = "/dev/disk/by-uuid/DC2AD3202AD2F68C";
    fsType = "ntfs";
    options = [
      "rw" "uid=1000" "gid=100" "umask=022"
      "nofail"        # 挂载失败不阻塞启动
      "x-systemd.device-timeout=5s" # 最多等待 5 秒
      "x-systemd.automount"         # 按需自动挂载（访问时才挂）
    ];
  };

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/3484d2dd-6350-4af5-a8f3-d8ca330a08ab";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/BD7A-EB01";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  hardware.graphics = {
    enable = true;
    extraPackages = with pkgs; [
      intel-compute-runtime
      intel-compute-runtime.drivers
      level-zero
      intel-media-driver
    ];
  };

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
